"""Human-readable audit report rendering."""

from __future__ import annotations

from kaji_langgraph.models import FinalResult

DISCLAIMER = (
    "This analysis was generated by an AI system and may contain errors. "
    "Always verify claims using primary sources and independent research."
)


def format_report(result: FinalResult) -> str:
    lines = [
        "=" * 64,
        "KajiSF-DJ — Evidence-driven Claim Analysis",
        "=" * 64,
        f"Claim: {result.claim}",
        f"Domain: {result.domain}",
        f"Reference date: {result.reference_date} ({result.reference_timezone})",
        f"Verdict: {result.verdict}",
        f"Confidence: {result.confidence}",
        f"Stop reason: {result.stop_reason}",
        "",
        "## Summary",
        "",
        result.summary or "No supported analysis was produced.",
        "",
    ]
    if result.evidence:
        lines.extend(["## Accepted evidence", ""])
        for index, item in enumerate(result.evidence, 1):
            lines.append(f"{index}. [{item.stance}] {item.finding}")
            for url in item.source_urls:
                lines.append(f"   - {url}")
                if item.quotes.get(url):
                    lines.append(f'     Quote: "{item.quotes[url]}"')
        lines.append("")
    if result.gaps:
        lines.extend(["## Unresolved gaps", ""])
        lines.extend(f"- {gap}" for gap in result.gaps)
        lines.append("")
    if result.contradictions:
        lines.extend(["## Contradictions", ""])
        lines.extend(f"- {item}" for item in result.contradictions)
        lines.append("")
    lines.extend(["## Research audit", ""])
    for item in result.research_history:
        lines.append(
            f"- Round {item.round_number}: {item.new_sources} new source(s), "
            f"proposed {item.proposed_verdict} ({item.confidence}), decision={item.decision}."
        )
        if item.queries:
            lines.append(f"  Queries: {', '.join(item.queries)}")
    lines.extend(
        [
            "",
            "## Resource audit",
            "",
            f"- Searches: {result.budget.search_calls}/{result.budget.max_search_calls}",
            f"- Full-page attempts: {result.budget.scrapes}/{result.budget.max_scrapes}",
            f"- Tokens observed: {result.budget.tokens_used}/{result.budget.max_tokens}",
            f"- Token accounting complete: {result.budget.token_usage_complete}",
            f"- Elapsed seconds: {result.elapsed_seconds:.2f}/{result.budget.max_seconds:.0f}",
            f"- Retrieval records: {len(result.retrieval_ledger)}",
        ]
    )
    if result.errors:
        lines.extend(["", "## Execution errors", ""])
        lines.extend(f"- {error}" for error in result.errors)
    lines.extend(["", "---", f"_{DISCLAIMER}_"])
    return "\n".join(lines)
